// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MTCS.Data.Models;

public partial class ContractFile
{
    public string FileId { get; set; }

    public string ContractId { get; set; }

    public string FileName { get; set; }

    public string FileType { get; set; }

    public DateTime? FileSize { get; set; }

    public byte[] FileContent { get; set; }

    public DateTime? UploadDate { get; set; }

    public string UploadBy { get; set; }

    public string Description { get; set; }

    public string Note { get; set; }

    public DateTime? DeletedDate { get; set; }

    public string DeletedBy { get; set; }

    public virtual Contract Contract { get; set; }
}