// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MTCS.Data.Models;

public partial class DeliveryStatus
{
    public string StatusId { get; set; }

    public string StatusName { get; set; }

    public int? IsActive { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? DeletedDate { get; set; }

    public string DeletedBy { get; set; }

    public int? StatusIndex { get; set; }

    public virtual ICollection<TripStatusHistory> TripStatusHistories { get; set; } = new List<TripStatusHistory>();
}