// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MTCS.Data.Models;

public partial class DeliveryStatus
{
    public string StatusId { get; set; }

    public string StatusName { get; set; }

    public virtual ICollection<TripStatusHistory> TripStatusHistories { get; set; } = new List<TripStatusHistory>();
}