// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MTCS.Data.Models;

public partial class DeliveryReport
{
    public string ReportId { get; set; }

    public string TripId { get; set; }

    public string Notes { get; set; }

    public DateTime? ReportTime { get; set; }

    public string ReportBy { get; set; }

    public virtual ICollection<DeliveryReportsFile> DeliveryReportsFiles { get; set; } = new List<DeliveryReportsFile>();
    [JsonIgnore]

    public virtual Trip Trip { get; set; }
}