// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MTCS.Data.Models;

public partial class DriverWeeklySummary
{
    public string SummaryId { get; set; }

    public string DriverId { get; set; }

    public DateOnly? WeekStart { get; set; }

    public DateOnly? WeekEnd { get; set; }

    public int? TotalHours { get; set; }

    public virtual Driver Driver { get; set; }
}