// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MTCS.Data.Models;

public partial class DriverDailyWorkingTime
{
    public string RecordId { get; set; }

    public string DriverId { get; set; }

    public DateOnly? WorkDate { get; set; }

    public int? TotalTime { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public virtual Driver Driver { get; set; }
}