// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MTCS.Data.Models;

public partial class ExpenseReportType
{
    public string ReportTypeId { get; set; }

    public string ReportType { get; set; }

    public int? IsActive { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public virtual ICollection<ExpenseReport> ExpenseReports { get; set; } = new List<ExpenseReport>();
}