// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MTCS.Data.Models;

public partial class ExpenseReport
{
    public string ReportId { get; set; }

    public string TripId { get; set; }

    public string ReportTypeId { get; set; }

    public decimal? Cost { get; set; }

    public string Location { get; set; }

    public DateTime? ReportTime { get; set; }

    public string ReportBy { get; set; }

    public int? IsPay { get; set; }

    public string Description { get; set; }

    public virtual ICollection<ExpenseReportFile> ExpenseReportFiles { get; set; } = new List<ExpenseReportFile>();

    public virtual ExpenseReportType ReportType { get; set; }

    public virtual Trip Trip { get; set; }
}