// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MTCS.Data.Models;

public partial class FuelReport
{
    public string ReportId { get; set; }

    public string TripId { get; set; }

    public decimal? RefuelAmount { get; set; }

    public decimal? FuelCost { get; set; }

    public string Location { get; set; }

    public DateTime? ReportTime { get; set; }

    public string ReportBy { get; set; }

    public string LicensePlate { get; set; }

    public virtual ICollection<FuelReportFile> FuelReportFiles { get; set; } = new List<FuelReportFile>();
    [JsonIgnore]

    public virtual Trip Trip { get; set; }
}