// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MTCS.Data.Models;

public partial class IncidentReportsFile
{
    public string FileId { get; set; }

    public string ReportId { get; set; }

    public string FileName { get; set; }

    public string FileType { get; set; }

    public DateTime? FileSize { get; set; }

    public DateTime? UploadDate { get; set; }

    public string UploadBy { get; set; }

    public string Description { get; set; }

    public string Note { get; set; }

    public DateTime? DeletedDate { get; set; }

    public string DeletedBy { get; set; }

    public string FileUrl { get; set; }

    public DateOnly? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public virtual IncidentReport Report { get; set; }
}