// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MTCS.Data.Models;

public partial class InspectionLog
{
    public string InspectionId { get; set; }

    public string TripId { get; set; }

    public string DriverId { get; set; }

    public string TractorStatus { get; set; }

    public string TrailerStatus { get; set; }

    public string VehicleRegistration { get; set; }

    public DateTime? InspectionDate { get; set; }

    public string Status { get; set; }

    public string Reason { get; set; }

    public virtual Trip Trip { get; set; }
}