// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace MTCS.Data.Models;

public partial class mtcsContext : DbContext
{
    public mtcsContext()
    {
    }

    public mtcsContext(DbContextOptions<mtcsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Contract> Contracts { get; set; }

    public virtual DbSet<ContractFile> ContractFiles { get; set; }

    public virtual DbSet<DeliveryReport> DeliveryReports { get; set; }

    public virtual DbSet<DeliveryReportsFile> DeliveryReportsFiles { get; set; }

    public virtual DbSet<DeliveryStatus> DeliveryStatuses { get; set; }

    public virtual DbSet<Driver> Drivers { get; set; }

    public virtual DbSet<DriverDailyWorkingTime> DriverDailyWorkingTimes { get; set; }

    public virtual DbSet<DriverFile> DriverFiles { get; set; }

    public virtual DbSet<FuelReport> FuelReports { get; set; }

    public virtual DbSet<FuelReportFile> FuelReportFiles { get; set; }

    public virtual DbSet<IncidentReport> IncidentReports { get; set; }

    public virtual DbSet<IncidentReportsFile> IncidentReportsFiles { get; set; }

    public virtual DbSet<InspectionLog> InspectionLogs { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderFile> OrderFiles { get; set; }

    public virtual DbSet<ShippingPrice> ShippingPrices { get; set; }

    public virtual DbSet<Token> Tokens { get; set; }

    public virtual DbSet<Tractor> Tractors { get; set; }

    public virtual DbSet<TractorCategory> TractorCategories { get; set; }

    public virtual DbSet<Trailer> Trailers { get; set; }

    public virtual DbSet<TrailerCategory> TrailerCategories { get; set; }

    public virtual DbSet<Trip> Trips { get; set; }

    public virtual DbSet<TripStatusHistory> TripStatusHistories { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<VehicleFile> VehicleFiles { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(GetConnectionString());
    }

    private string GetConnectionString()
    {
        IConfiguration configuration = new ConfigurationBuilder()
        .SetBasePath(Directory.GetCurrentDirectory())
        .AddJsonFile("appsettings.json", true, true).Build();
        return configuration["ConnectionStrings:DefaultConnection"];
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Contract>(entity =>
        {
            entity.HasKey(e => e.ContractId).HasName("PK__Contract__C90D34695F198265");

            entity.ToTable("Contract");

            entity.Property(e => e.ContractId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.StartDate).HasColumnType("datetime");
            entity.Property(e => e.UserId)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.User).WithMany(p => p.Contracts)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Contract__UserId__656C112C");
        });

        modelBuilder.Entity<ContractFile>(entity =>
        {
            entity.HasKey(e => e.FileId).HasName("PK__Contract__6F0F98BF0D768B98");

            entity.ToTable("ContractFile");

            entity.Property(e => e.FileId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.ContractId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.FileName).IsUnicode(false);
            entity.Property(e => e.FileSize).HasColumnType("datetime");
            entity.Property(e => e.FileType).IsUnicode(false);
            entity.Property(e => e.Note).HasMaxLength(255);
            entity.Property(e => e.UploadDate).HasColumnType("datetime");

            entity.HasOne(d => d.Contract).WithMany(p => p.ContractFiles)
                .HasForeignKey(d => d.ContractId)
                .HasConstraintName("FK__ContractF__Contr__68487DD7");
        });

        modelBuilder.Entity<DeliveryReport>(entity =>
        {
            entity.HasKey(e => e.ReportId).HasName("PK__Delivery__D5BD4805E3ECD3CE");

            entity.Property(e => e.ReportId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.ReportTime).HasColumnType("datetime");
            entity.Property(e => e.TripId)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.Trip).WithMany(p => p.DeliveryReports)
                .HasForeignKey(d => d.TripId)
                .HasConstraintName("FK__DeliveryR__TripI__160F4887");
        });

        modelBuilder.Entity<DeliveryReportsFile>(entity =>
        {
            entity.HasKey(e => e.FileId).HasName("PK__Delivery__6F0F98BF9434B533");

            entity.ToTable("DeliveryReportsFile");

            entity.Property(e => e.FileId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.FileName).IsUnicode(false);
            entity.Property(e => e.FileSize).HasColumnType("datetime");
            entity.Property(e => e.FileType).IsUnicode(false);
            entity.Property(e => e.Note).HasMaxLength(255);
            entity.Property(e => e.ReportId)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.UploadDate).HasColumnType("datetime");

            entity.HasOne(d => d.Report).WithMany(p => p.DeliveryReportsFiles)
                .HasForeignKey(d => d.ReportId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DeliveryR__Repor__18EBB532");
        });

        modelBuilder.Entity<DeliveryStatus>(entity =>
        {
            entity.HasKey(e => e.StatusId).HasName("PK__Delivery__C8EE20637B5FD383");

            entity.ToTable("DeliveryStatus");

            entity.Property(e => e.StatusId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.StatusName)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<Driver>(entity =>
        {
            entity.HasKey(e => e.DriverId).HasName("PK__Driver__F1B1CD04131B0750");

            entity.ToTable("Driver");

            entity.Property(e => e.DriverId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.DeletedBy).IsUnicode(false);
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
            entity.Property(e => e.Email).IsUnicode(false);
            entity.Property(e => e.FullName).IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Password).HasMaxLength(255);
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        modelBuilder.Entity<DriverDailyWorkingTime>(entity =>
        {
            entity.HasKey(e => e.RecordId).HasName("PK__DriverDa__FBDF78E95831D941");

            entity.ToTable("DriverDailyWorkingTime");

            entity.Property(e => e.RecordId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.DriverId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedBy).HasMaxLength(100);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Driver).WithMany(p => p.DriverDailyWorkingTimes)
                .HasForeignKey(d => d.DriverId)
                .HasConstraintName("FK__DriverDai__Drive__22751F6C");
        });

        modelBuilder.Entity<DriverFile>(entity =>
        {
            entity.HasKey(e => e.FileId).HasName("PK__DriverFi__6F0F98BF7E05AABD");

            entity.ToTable("DriverFile");

            entity.Property(e => e.FileId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.DriverId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.FileName).IsUnicode(false);
            entity.Property(e => e.FileSize).HasColumnType("datetime");
            entity.Property(e => e.FileType).IsUnicode(false);
            entity.Property(e => e.Note).HasMaxLength(255);
            entity.Property(e => e.UploadDate).HasColumnType("datetime");

            entity.HasOne(d => d.Driver).WithMany(p => p.DriverFiles)
                .HasForeignKey(d => d.DriverId)
                .HasConstraintName("FK__DriverFil__Drive__628FA481");
        });

        modelBuilder.Entity<FuelReport>(entity =>
        {
            entity.HasKey(e => e.ReportId).HasName("PK__FuelRepo__D5BD4805641BE5DD");

            entity.ToTable("FuelReport");

            entity.Property(e => e.ReportId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.FuelCost).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.RefuelAmount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ReportTime).HasColumnType("datetime");
            entity.Property(e => e.TripId)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.Trip).WithMany(p => p.FuelReports)
                .HasForeignKey(d => d.TripId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__FuelRepor__TripI__07C12930");
        });

        modelBuilder.Entity<FuelReportFile>(entity =>
        {
            entity.HasKey(e => e.FileId).HasName("PK__FuelRepo__6F0F98BF272220FD");

            entity.ToTable("FuelReportFile");

            entity.Property(e => e.FileId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.FileName).IsUnicode(false);
            entity.Property(e => e.FileSize).HasColumnType("datetime");
            entity.Property(e => e.FileType).IsUnicode(false);
            entity.Property(e => e.Note).HasMaxLength(255);
            entity.Property(e => e.ReportId)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.UploadBy).IsUnicode(false);
            entity.Property(e => e.UploadDate).HasColumnType("datetime");

            entity.HasOne(d => d.Report).WithMany(p => p.FuelReportFiles)
                .HasForeignKey(d => d.ReportId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__FuelRepor__Repor__0A9D95DB");
        });

        modelBuilder.Entity<IncidentReport>(entity =>
        {
            entity.HasKey(e => e.ReportId).HasName("PK__Incident__D5BD48058957656C");

            entity.Property(e => e.ReportId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.HandledBy)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.HandledTime).HasColumnType("datetime");
            entity.Property(e => e.IncidentTime).HasColumnType("datetime");
            entity.Property(e => e.IncidentType)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ReportedBy)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Pending");
            entity.Property(e => e.TripId)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.Trip).WithMany(p => p.IncidentReports)
                .HasForeignKey(d => d.TripId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__IncidentR__TripI__1CBC4616");
        });

        modelBuilder.Entity<IncidentReportsFile>(entity =>
        {
            entity.HasKey(e => e.FileId).HasName("PK__Incident__6F0F98BFE1E93A8A");

            entity.ToTable("IncidentReportsFile");

            entity.Property(e => e.FileId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.FileName).IsUnicode(false);
            entity.Property(e => e.FileSize).HasColumnType("datetime");
            entity.Property(e => e.FileType).IsUnicode(false);
            entity.Property(e => e.Note).HasMaxLength(255);
            entity.Property(e => e.ReportId)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.UploadDate).HasColumnType("datetime");

            entity.HasOne(d => d.Report).WithMany(p => p.IncidentReportsFiles)
                .HasForeignKey(d => d.ReportId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__IncidentR__Repor__1F98B2C1");
        });

        modelBuilder.Entity<InspectionLog>(entity =>
        {
            entity.HasKey(e => e.InspectionId).HasName("PK__Inspecti__30B2DC08ACA20906");

            entity.Property(e => e.InspectionId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.DriverId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.InspectionDate).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TractorStatus)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TrailerStatus)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TripId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.VehicleRegistration)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Trip).WithMany(p => p.InspectionLogs)
                .HasForeignKey(d => d.TripId)
                .HasConstraintName("FK__Inspectio__TripI__0D7A0286");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__Orders__C3905BCF01DA6AEF");

            entity.Property(e => e.OrderId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.DeliveryLocation).IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.PickUpLocation).IsUnicode(false);
            entity.Property(e => e.PriceId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Pending");
            entity.Property(e => e.Temperature).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.TrackingCode).IsUnicode(false);
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Weight).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Price).WithMany(p => p.Orders)
                .HasForeignKey(d => d.PriceId)
                .HasConstraintName("FK__Orders__PriceId__7C4F7684");

            entity.HasOne(d => d.User).WithMany(p => p.Orders)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Orders__UserId__7B5B524B");
        });

        modelBuilder.Entity<OrderFile>(entity =>
        {
            entity.HasKey(e => e.FileId).HasName("PK__OrderFil__6F0F98BFB5C36FFA");

            entity.ToTable("OrderFile");

            entity.Property(e => e.FileId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.FileName).IsUnicode(false);
            entity.Property(e => e.FileSize).HasColumnType("datetime");
            entity.Property(e => e.FileType).IsUnicode(false);
            entity.Property(e => e.Note).HasMaxLength(255);
            entity.Property(e => e.OrderId)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.UploadDate).HasColumnType("datetime");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderFiles)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderFile__Order__7F2BE32F");
        });

        modelBuilder.Entity<ShippingPrice>(entity =>
        {
            entity.HasKey(e => e.PriceId).HasName("PK__Shipping__49575BAF80BF5AF9");

            entity.Property(e => e.PriceId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy).HasMaxLength(100);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.PricePerKm).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<Token>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("Token");

            entity.Property(e => e.AccessToken).IsUnicode(false);
            entity.Property(e => e.ExpiredTime).HasColumnType("datetime");
            entity.Property(e => e.RefreshToken).IsUnicode(false);
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Tractor>(entity =>
        {
            entity.HasKey(e => e.TractorId).HasName("PK__Tractor__46B2DC30F327396B");

            entity.ToTable("Tractor");

            entity.Property(e => e.TractorId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Brand)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.DeletedBy).HasMaxLength(100);
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
            entity.Property(e => e.LastMaintenanceDate).HasColumnType("datetime");
            entity.Property(e => e.LicensePlate)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.MaxLoadWeight).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Model)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedBy).HasMaxLength(100);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.NextMaintenanceDate).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TractorCateId)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.TractorCate).WithMany(p => p.Tractors)
                .HasForeignKey(d => d.TractorCateId)
                .HasConstraintName("FK__Tractor__Tractor__6D0D32F4");
        });

        modelBuilder.Entity<TractorCategory>(entity =>
        {
            entity.HasKey(e => e.TractorCateId).HasName("PK__TractorC__6E3E5B5F06193134");

            entity.ToTable("TractorCategory");

            entity.Property(e => e.TractorCateId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.CategoryName).HasMaxLength(100);
        });

        modelBuilder.Entity<Trailer>(entity =>
        {
            entity.HasKey(e => e.TrailerId).HasName("PK__Trailer__1B041D2340859B60");

            entity.ToTable("Trailer");

            entity.Property(e => e.TrailerId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Brand)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.DeletedBy).HasMaxLength(100);
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
            entity.Property(e => e.LastMaintenanceDate).HasColumnType("datetime");
            entity.Property(e => e.Length).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.LicensePlate)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.MaxLoadWeight).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Model)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedBy).HasMaxLength(100);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.NextMaintenanceDate).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TrailerCateId)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.TrailerCate).WithMany(p => p.Trailers)
                .HasForeignKey(d => d.TrailerCateId)
                .HasConstraintName("FK__Trailer__Trailer__71D1E811");
        });

        modelBuilder.Entity<TrailerCategory>(entity =>
        {
            entity.HasKey(e => e.TrailerCateId).HasName("PK__TrailerC__CC3B6FBC2FBB89FD");

            entity.ToTable("TrailerCategory");

            entity.Property(e => e.TrailerCateId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.CategoryName).HasMaxLength(100);
        });

        modelBuilder.Entity<Trip>(entity =>
        {
            entity.HasKey(e => e.TripId).HasName("PK__Trips__51DC713E5E83DD00");

            entity.Property(e => e.TripId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Distance).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.DriverId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.EndTime).HasColumnType("datetime");
            entity.Property(e => e.MatchBy).HasMaxLength(255);
            entity.Property(e => e.OrderId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.StartTime).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.TractorId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.TrailerId)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.Driver).WithMany(p => p.Trips)
                .HasForeignKey(d => d.DriverId)
                .HasConstraintName("FK__Trips__DriverId__02FC7413");

            entity.HasOne(d => d.Order).WithMany(p => p.Trips)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK__Trips__OrderId__02084FDA");

            entity.HasOne(d => d.Tractor).WithMany(p => p.Trips)
                .HasForeignKey(d => d.TractorId)
                .HasConstraintName("FK__Trips__TractorId__03F0984C");

            entity.HasOne(d => d.Trailer).WithMany(p => p.Trips)
                .HasForeignKey(d => d.TrailerId)
                .HasConstraintName("FK__Trips__TrailerId__04E4BC85");
        });

        modelBuilder.Entity<TripStatusHistory>(entity =>
        {
            entity.HasKey(e => e.HistoryId).HasName("PK__TripStat__4D7B4ABDC197EC4A");

            entity.ToTable("TripStatusHistory");

            entity.Property(e => e.HistoryId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.ChangeTime).HasColumnType("datetime");
            entity.Property(e => e.StatusId)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.TripId)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.Status).WithMany(p => p.TripStatusHistories)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TripStatu__Statu__1332DBDC");

            entity.HasOne(d => d.Trip).WithMany(p => p.TripStatusHistories)
                .HasForeignKey(d => d.TripId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TripStatu__TripI__123EB7A3");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CC4C0E125DFF");

            entity.Property(e => e.UserId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
            entity.Property(e => e.Email).IsUnicode(false);
            entity.Property(e => e.FullName).HasMaxLength(255);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Password).HasMaxLength(255);
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Role)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<VehicleFile>(entity =>
        {
            entity.HasKey(e => e.FileId).HasName("PK__VehicleF__6F0F98BF8528278A");

            entity.ToTable("VehicleFile");

            entity.Property(e => e.FileId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.FileName).IsUnicode(false);
            entity.Property(e => e.FileSize).HasColumnType("datetime");
            entity.Property(e => e.FileType).IsUnicode(false);
            entity.Property(e => e.Note).HasMaxLength(255);
            entity.Property(e => e.TractorsId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.TrailerId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.UploadBy).IsUnicode(false);
            entity.Property(e => e.UploadDate).HasColumnType("datetime");

            entity.HasOne(d => d.Tractors).WithMany(p => p.VehicleFiles)
                .HasForeignKey(d => d.TractorsId)
                .HasConstraintName("FK__VehicleFi__Tract__74AE54BC");

            entity.HasOne(d => d.Trailer).WithMany(p => p.VehicleFiles)
                .HasForeignKey(d => d.TrailerId)
                .HasConstraintName("FK__VehicleFi__Trail__75A278F5");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}