// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MTCS.Data.Models;

public partial class Order
{
    public string OrderId { get; set; }

    public string TrackingCode { get; set; }

    public string UserId { get; set; }

    public string PriceId { get; set; }

    public decimal? Temperature { get; set; }

    public decimal? Weight { get; set; }

    public DateOnly? PickUpDate { get; set; }

    public DateOnly? DeliveryDate { get; set; }

    public string PickUpLocation { get; set; }

    public string DeliveryLocation { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public virtual ICollection<OrderFile> OrderFiles { get; set; } = new List<OrderFile>();

    public virtual ShippingPrice Price { get; set; }

    public virtual ICollection<Trip> Trips { get; set; } = new List<Trip>();

    public virtual User User { get; set; }
}