// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MTCS.Data.Models;

public partial class OrderDetail
{
    public string OrderDetailId { get; set; }

    public string OrderId { get; set; }

    public string ContainerNumber { get; set; }

    public int? ContainerType { get; set; }

    public int? ContainerSize { get; set; }

    public decimal? Weight { get; set; }

    public decimal? Temperature { get; set; }

    public string PickUpLocation { get; set; }

    public string DeliveryLocation { get; set; }

    public string ConReturnLocation { get; set; }

    public TimeOnly? CompletionTime { get; set; }

    public decimal? Distance { get; set; }

    public string Status { get; set; }

    public DateOnly? PickUpDate { get; set; }

    public DateOnly? DeliveryDate { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<OrderDetailFile> OrderDetailFiles { get; set; } = new List<OrderDetailFile>();
}