// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MTCS.Data.Models;

public partial class Order
{
    public string OrderId { get; set; }

    public string TrackingCode { get; set; }

    public string CustomerId { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public string ContactPerson { get; set; }

    public string ContactPhone { get; set; }

    public string OrderPlacer { get; set; }

    public int? IsPay { get; set; }

    public int? TotalAmount { get; set; }

    public int? Quantity { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<Trip> Trips { get; set; } = new List<Trip>();
}