// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MTCS.Data.Models;

public partial class PriceTable
{
    public string PriceId { get; set; }

    public double? MinKm { get; set; }

    public double? MaxKm { get; set; }

    public int? ContainerSize { get; set; }

    public int? ContainerType { get; set; }

    public decimal? MinPricePerKm { get; set; }

    public decimal? MaxPricePerKm { get; set; }

    public int? Status { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public int? DeliveryType { get; set; }
}