// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MTCS.Data.Models;

public partial class ShippingPrice
{
    public string PriceId { get; set; }

    public int ContainerSize { get; set; }

    public int Type { get; set; }

    public decimal PricePerKm { get; set; }

    public int? IsActive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}