// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MTCS.Data.Models;

public partial class TrailerFile
{
    public string FileId { get; set; }

    public string TrailerId { get; set; }

    public string FileName { get; set; }

    public string FileType { get; set; }

    public byte[] FileContent { get; set; }

    public DateTime? UploadDate { get; set; }

    public string UploadBy { get; set; }

    public string Description { get; set; }

    public string Note { get; set; }

    public DateTime? DeletedDate { get; set; }

    public string DeletedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public virtual Trailer Trailer { get; set; }
}