// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MTCS.Data.Models;

public partial class Trailer
{
    public string TrailerId { get; set; }

    public string LicensePlate { get; set; }

    public string Brand { get; set; }

    public int? ManufactureYear { get; set; }

    public decimal? MaxLoadWeight { get; set; }

    public DateTime? LastMaintenanceDate { get; set; }

    public DateTime? NextMaintenanceDate { get; set; }

    public DateOnly? RegistrationDate { get; set; }

    public DateOnly? RegistrationExpirationDate { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? DeletedDate { get; set; }

    public string DeletedBy { get; set; }

    public int? ContainerSize { get; set; }

    public virtual ICollection<TrailerFile> TrailerFiles { get; set; } = new List<TrailerFile>();

    public virtual ICollection<Trip> Trips { get; set; } = new List<Trip>();
}