// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MTCS.Data.Models;

public partial class TrailerCategory
{
    public string TrailerCateId { get; set; }

    public string CategoryName { get; set; }

    public virtual ICollection<Trailer> Trailers { get; set; } = new List<Trailer>();
}