// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MTCS.Data.Models;

public partial class Trip
{
    public string TripId { get; set; }

    public string OrderId { get; set; }

    public string DriverId { get; set; }

    public string TractorId { get; set; }

    public string TrailerId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public string Status { get; set; }

    public decimal? Distance { get; set; }

    public int? MatchType { get; set; }

    public string MatchBy { get; set; }

    public DateTime? MatchTime { get; set; }

    public virtual ICollection<DeliveryReport> DeliveryReports { get; set; } = new List<DeliveryReport>();

    public virtual Driver Driver { get; set; }

    public virtual ICollection<FuelReport> FuelReports { get; set; } = new List<FuelReport>();

    public virtual ICollection<IncidentReport> IncidentReports { get; set; } = new List<IncidentReport>();

    public virtual ICollection<InspectionLog> InspectionLogs { get; set; } = new List<InspectionLog>();

    public virtual Order Order { get; set; }

    public virtual Tractor Tractor { get; set; }

    public virtual Trailer Trailer { get; set; }

    public virtual ICollection<TripStatusHistory> TripStatusHistories { get; set; } = new List<TripStatusHistory>();
}