// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MTCS.Data.Models;

public partial class TripStatusHistory
{
    public string HistoryId { get; set; }

    public string TripId { get; set; }

    public string StatusId { get; set; }

    public DateTime? StartTime { get; set; }

    public int? StatusIndex { get; set; }

    public virtual DeliveryStatus Status { get; set; }

    public virtual Trip Trip { get; set; }
}